[package]
name = "spicy-launcher-cli"
version = "0.1.2"
description = "Cross-platform launcher for Spicy Lobster games (CLI)"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "3.2.12", features = ["derive", "env"] }
anyhow = "1.0.58"
tokio = { version = "1.20.0", features = ["full"] }
pretty_env_logger = "0.4.0"
log = "0.4.17"
indicatif = "0.16.2"
colored = "2.0.0"

[dependencies.spicy-launcher-core]
path = "../core"
