[package]
name = "fishfight-launcher-cli"
version = "0.1.0"
description = "A cross-platform launcher for Fish Fight (CLI)"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "3.0.10", features = ["derive", "env"] }
anyhow = "1.0.45"
tokio = { version = "1.13.0", features = ["full"] }

[dependencies.fishfight-launcher-core]
path = "../core"
