[package]
name = "spicy-launcher-core"
version = "0.1.2"
description = "Core library of the Spicy Lobster launcher"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.11", features = ["json", "stream"] }
thiserror = "1.0.31"
serde = { version = "1.0.139", features = ["derive"] }
dirs-next = "2.0.0"
platforms = "3.0.0"
guess_host_triple = "0.1.3"
bytesize = "1.1.0"
flate2 = "1.0.24"
tar = "0.4.38"
zip = "0.6.2"
ring = "0.16.20"
log = "0.4.14"
futures-util = "0.3.19"
