[package]
name = "fishfight-launcher-core"
version = "0.1.0"
description = "Core library of the Fish Fight launcher"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
edition = "2021"

[dependencies]
