[package]
name = "fishfight-launcher-core"
version = "0.1.0"
description = "Core library of the Fish Fight launcher"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
edition = "2021"

[dependencies]
reqwest = { version = "0.11.6", features = ["json"] }
thiserror = "1.0.30"
serde = { version = "1.0.130", features = ["derive"] }
dirs-next = "2.0.0"
platforms = "2.0.0"
bytesize = "1.1.0"
flate2 = "1.0.22"
tar = "0.4.38"
zip-extract = "0.1.1"
ring = "0.16.20"
